name: MobileTradeIn-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: windows-latest

variables:
- group: MobileTradeIn-DEV

- name: BuildConfiguration
  value: Release

- name: DotNetVersion
  value: 9.0.x

stages:

#==========================
# BUILD
#==========================
- stage: Build
  displayName: Build Stage

  jobs:

  - job: Build

    steps:

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: sdk
        version: $(DotNetVersion)

    - task: AzureKeyVault@2
      displayName: 'Download secrets from Azure Key Vault'
      inputs:
        azureSubscription: 'MobileTradeIn-ServiceConnection'
        KeyVaultName: 'kv-mobiletradein-dev'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.sln'
        arguments: '--configuration $(BuildConfiguration) --no-restore'

#==========================
# TEST
#==========================
- stage: Test
  displayName: Test Stage

  dependsOn: Build

  jobs:

  - job: Test

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(DotNetVersion)

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: >
          --configuration $(BuildConfiguration)
          --collect:"XPlat Code Coverage"
          --logger trx

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/*.trx'

    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '**/coverage.cobertura.xml'

#==========================
# PUBLISH
#==========================
- stage: Publish
  displayName: Publish Stage

  dependsOn: Test

  jobs:

  - job: Publish

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(DotNetVersion)

    - task: DotNetCoreCLI@2
      displayName: Publish API
      inputs:
        command: publish
        publishWebProjects: true
        arguments: >
          --configuration $(BuildConfiguration)
          --output $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: MobileTradeIn