name: MobileTradeIn-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: windows-latest

variables:

- group: MobileTradeIn-DEV

- name: BuildConfiguration
  value: Release

- name: DotNetVersion
  value: 9.0.x

steps:

# Install .NET SDK
- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: sdk
    version: $(DotNetVersion)

# Restore
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.sln'

# Build
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

# Unit Test
- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: >
      --configuration $(BuildConfiguration)
      --collect:"XPlat Code Coverage"
      --logger trx
      --no-build

# Publish Test Result
- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

# Publish Coverage
- task: PublishCodeCoverageResults@2
  displayName: Publish Code Coverage
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/coverage.cobertura.xml'

# Publish API
- task: DotNetCoreCLI@2
  displayName: Publish API
  inputs:
    command: publish
    publishWebProjects: true
    arguments: >
      --configuration $(BuildConfiguration)
      --output $(Build.ArtifactStagingDirectory)

# Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: MobileTradeIn